### ISSUE TITLE
DOWNLOADING FILE TO SERVER

### ISSUE THREAD

**Issue by frencymontana** [TerminalWarlord/TikTok-Downloader-Bot#8]
Bot stuck on "Downloading file to server"

**Comment by vheske** [comment]
> Bot stuck on "Downloading file to server"

Same

**Comment by TerminalWarlord** [comment]
> Bot stuck on "Downloading file to server"

go to [RapidAPI](https://rapidapi.com/TerminalWarlord/api/tiktok-info/) and create an account. Use add your credentials on [line 71](https://github.com/TerminalWarlord/TikTok-Downloader-Bot/blob/74e6f97d942c01073a4610a1dbd987dcb483af57/main.py#L71) and you're good to go.

**Comment by denzardten** [comment]
nothing changed

2022-07-16T17:24:29.876680+00:00 app[worker.1]: Traceback (most recent call last):
2022-07-16T17:24:29.876682+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/dispatcher.py", line 210, in handler_worker
2022-07-16T17:24:29.876682+00:00 app[worker.1]:     await self.loop.run_in_executor(
2022-07-16T17:24:29.876687+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/concurrent/futures/thread.py", line 57, in run
2022-07-16T17:24:29.876687+00:00 app[worker.1]:     result = self.fn(*self.args, **self.kwargs)
2022-07-16T17:24:29.876688+00:00 app[worker.1]:   File "main.py", line 82, in tiktok_dl
2022-07-16T17:24:29.876688+00:00 app[worker.1]:     size = int(requests.head(r).headers['Content-length'])
2022-07-16T17:24:29.876689+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/requests/structures.py", line 52, in __getitem__
2022-07-16T17:24:29.876689+00:00 app[worker.1]:     return self._store[key.lower()][1]
2022-07-16T17:24:29.876689+00:00 app[worker.1]: KeyError: 'content-length'
